### ISSUE TITLE
problem when importing

### ISSUE THREAD

**Issue by D063520** [the-qa-company/WikibaseSync#9]
```Error probably property or item already existing  Edit to page [[my:Property:-1]] failed:
modification-failed: Property [[Property:P3|P3]] already has label "Dewey Decimal Classification" associated with language code en.
[messages: [{'name': 'wikibase-validator-label-conflict', 'parameters': ['Dewey Decimal Classification', 'en', '[[Property:P3|P3]]'], 'html': {'*': 'Property <a href="/wiki/Property:P3" title="Property:P3">P3</a> already has label "Dewey Decimal Classification" associated with language code en.'}}];
 help: See http://localhost/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.]
Traceback (most recent call last):
  File "import_one.py", line 27, in <module>
    wikibase_importer.change_item(wikidata_item, wikibase_repo, True)
  File "/Users/Dennis/PycharmProjects/WikibaseSync/util/util.py", line 1078, in change_item
    self.changeClaims(wikidata_item, wikibase_item)
  File "/Users/Dennis/PycharmProjects/WikibaseSync/util/util.py", line 992, in changeClaims
    claim = self.translateClaim(wikidata_claim.get('mainsnak'))
  File "/Users/Dennis/PycharmProjects/WikibaseSync/util/util.py", line 733, in translateClaim
    claim = pywikibot.page.Claim(self.wikibase_repo, self.id.get_id(wikidata_propertyId),
  File "/Users/Dennis/PycharmProjects/WikibaseSync/util/IdSparql.py", line 52, in get_id
    return self.mapProperty[id]
KeyError: 'P1036'
```

**Comment by D063520** [comment]
This happened to me when I did not clean properly my previews Wikibase Tests instance. With the following line you will delete all previously created data

docker-compose -f docker-compose.yml -f docker-compose.extra.yml down -v

WARNING: all your data will be lost. Take care!

**Comment by D063520** [comment]
This could also happen when launching an import directly one after the other. Some data is fetched from the SPARQL endpoint and this is lagging at least 2-10 seconds behind the wikibase. So WikibaseSync might import something that is already there and cannot now because of a lag of the SPARQL endpoint.
